apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "currency:9091"
        "consul.hashicorp.com/connect-service-protocol": "http"
        "consul.hashicorp.com/service-meta-version": "2"
    spec:
      containers:
      - name: payments
        image: nicholasjackson/fake-service:v0.9.0
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "UPSTREAM_URIS"
          value: "http://127.0.0.1:9091"
        - name: "NAME"
          value: "payments v2"
        - name: "MESSAGE"
          value: "payment complete"

---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090